trigger:
- master
- release

pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:

# - job: 'Linux'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - script: sudo apt install libxkbcommon-x11-0
#     displayName: 'Install libxkbcommon-x11-0'
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '3.7'
#     displayName: 'Use Python 3.7'
#   - script: |
#       python -m pip install --upgrade pip setuptools wheel
#       python -m pip install -r requirements.txt
#       python -m pip install pytest pytest-azurepipelines pytest-faulthandler pytest-qt
#       python -m pip install git+git://github.com/ponty/PyVirtualDisplay.git
#       python -m pip install git+git://github.com/The-Compiler/pytest-xvfb.git
#     displayName: 'Install dependencies'
#   - script: python setup.py develop
#     displayName: 'Install blockbuilder'
#   - script: pytest -s blockbuilder/tests
#     displayName: 'Run tests'

- job: 'Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'
      addToPath: true
    displayName: 'Setup Python'
  - powershell: .\install_opengl.ps1
    displayName: 'Install OpenGL'
  - bash: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements_testing.txt
    displayName: 'Install dependencies'
  - bash: |
      pip install -e .
    displayName: 'Install blockbuilder'
  - bash: |
      pytest -v blockbuilder
    displayName: 'Run tests'
