trigger:
- master
- release

pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:

- job: 'Style'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'
      addToPath: true
    displayName: 'Setup Python'
  - bash: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install dependencies'
  - bash: pip install codespell
    displayName: 'Install codespell'
  - bash: make codespell
    displayName: 'Run codespell'
  - bash: pip install pydocstyle
    displayName: 'Install pydocstyle'
  - bash: make pydocstyle
    displayName: 'Run pydocstyle'

- job: 'Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'
      addToPath: true
    displayName: 'Setup Python'
  - powershell: .\install_opengl.ps1
    displayName: 'Install OpenGL'
  - bash: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements_testing.txt
    displayName: 'Install dependencies'
  - bash: pip install -e .
    displayName: 'Install blockbuilder'
  - bash: pytest -v blockbuilder -n 1
    displayName: 'Run tests'

# - job: 'Linux'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - script: sudo apt install libxkbcommon-x11-0
#     displayName: 'Install libxkbcommon-x11-0'
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '3.7'
#       architecture: 'x64'
#       addToPath: true
#     displayName: 'Setup Python'
#   - bash: |
#       python -m pip install --upgrade pip setuptools wheel
#       pip install -r requirements_testing.txt
#       pip install pytest-azurepipelines pytest-faulthandler pytest-xvfb
#     displayName: 'Install dependencies'
#   - bash: pip install -e .
#     displayName: 'Install blockbuilder'
#   - bash: pytest -v blockbuilder -n 1
#     displayName: 'Run tests'
