trigger:
- master
- develop

pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:

- job: Code style
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Python37-64bit:
        PYTHON_VERSION: '3.7'
        PYTHON_ARCH: 'x64'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      architecture: $(PYTHON_ARCH)
      addToPath: true
    displayName: 'Setup Python $(PYTHON_VERSION)'
  - bash: |
      python -m pip install --upgrade pip setuptools
    displayName: 'Install dependencies'
    condition: always()
  - bash: |
      pip install codespell
    displayName: 'Install codespell'
    condition: always()
  - bash: |
      make codespell
    displayName: 'Run codespell'
    condition: always()
  - bash: |
      pip install pydocstyle
    displayName: 'Install pydocstyle'
    condition: always()
  - bash: |
      make pydocstyle
    displayName: 'Run pydocstyle'
    condition: always()
