trigger:
- master
- release

pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:

- job: 'Style'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'
      addToPath: true
    displayName: 'Setup python'
  - bash: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install dependencies'
  - bash: pip install codespell
    displayName: 'Install codespell'
  - bash: make codespell
    displayName: 'Run codespell'
  - bash: pip install pydocstyle
    displayName: 'Install pydocstyle'
  - bash: make pydocstyle
    displayName: 'Run pydocstyle'

- job: 'Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'
      addToPath: true
    displayName: 'Setup python'
  - powershell: .\install_opengl.ps1
    displayName: 'Install opengl'
  - bash: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements_testing.txt
      pip install PyQt5
    displayName: 'Install dependencies'
  - bash: pip install -e .
    displayName: 'Install blockbuilder'
  - bash: pytest -v blockbuilder -n 1
    displayName: 'Run tests'

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    DISPLAY: ':99'
  steps:
  - bash: |
      sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
    displayName: 'Setup xvfb'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
      addToPath: true
    displayName: 'Setup python'
  - bash: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements_testing.txt
      pip install PyQt5
    displayName: 'Install dependencies'
  - bash: pip install -e .
    displayName: 'Install blockbuilder'
  - bash: pytest -v blockbuilder -n 1
    displayName: 'Run tests'
