name: MacOS
on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master

jobs:
  macos-pip:
    name: py${{ matrix.python.name }}-${{ matrix.qt_api.name }}-qt${{ matrix.qt_version.name }}-vtk${{ matrix.vtk_version.name }}
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - name: '3.7'
          - name: '3.8'
        qt_api:
          - name: 'PyQt5'
          - name: 'PySide2'
        qt_version:
          - name: '5.14.2'
          - name: '5.15.2'
        vtk_version:
          - name: '9.0.1'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python.name }}
          architecture: 'x64'
        name: 'Setup python'
      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ${{ matrix.qt_api.name }}==${{ matrix.qt_version.name }}
          pip install -r requirements_testing.txt
          pip install vtk==${{ matrix.vtk_version.name }}
        name: 'Install dependencies'
      - run: pip install -e .
        name: 'Install blockbuilder'
      - run: pytest -v blockbuilder -n 1
        name: 'Run tests'
