name: Testing
on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: python -m pip install --upgrade pip setuptools wheel
        name: 'Install dependencies'
      - run: pip install codespell
        name: 'Install codespell'
      - run: make codespell
        name: 'Run codespell'
      - run: pip install pydocstyle
        name: 'Install pydocstyle'
      - run: make pydocstyle
        name: 'Run pydocstyle'

  windows-py38-64bit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: .\install_opengl.ps1
        shell: pwsh
        name: 'Install OpenGL'
      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_testing.txt
        name: 'Install dependencies'
      - run: pip install -e .
        name: 'Install blockbuilder'
      - run: pytest -v blockbuilder -n 1
        name: 'Run tests'

  # coverage-codacy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.7'
  #         architecture: 'x64'
  #     - run: python -m pip install --upgrade pip setuptools
  #     - run: pip install -r requirements_testing.txt
  #     - run: pip install -e .
  #     - run: make coverage-codacy
  #     - name: Run codacy-coverage-reporter
  #       uses: codacy/codacy-coverage-reporter-action@master
  #       with:
  #         project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  #         coverage-reports: cobertura.xml
        
  # ubuntu-py37-64bit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.7'
  #         architecture: 'x64'
  #     - run: python -m pip install --upgrade pip setuptools
  #      - run: |
  #          pip install -r requirements_testing.txt
  #          pip install -e .
  #     - run: pytest -v blockbuilder
